# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3762093ff9f4269eefbf1facd93836de2e051e9d9b3c6419fcda907b3bffcf3d7a9c1d8fce15efedb918af8d77ff32c5cd52da1cea87a60a36bdd5bbec41f87

test:
  secret_key_base: 980387cff126b4abd2cd6f4715ba3c1a5c0df190c9e5c9dfa6cfd150601225372ef26312d7c6086565b16cf89e4ae20d368e85f4425297e059bf8c88055fae60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
